name: "pecologs"
shortDesc: "'kubectl logs' for multiple containers by specifing query and peco"
longDesc: "output container logs of containers specifying by query and  peco."
example: "pecologs --since=1s query"
command: "./pecologs.sh"
flags:
  - name: "interactive"
    shorthand: "i"
    desc: "if you set false, you can skip peco."
    defValue: "true"
  - name: "since"
    desc: "Only return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to all."
    defValue: "1s"
  - name: "dry-run"
    desc: "dry run mode. just print out commands to be executed."
    defValue: "false"
